### PR TITLE
Unity 5 Update. Tag functionality. GoDataType.cs

### PR DESCRIPTION
**Pull request by rygo6**
Let Unity 5 run automatic API update.

Created class GoDataType which is a container of base data types that one can instance and then tween around if they only desire to tween a base type. Or if they desire a base type to tween that can be passed into other methods in setOnUpdateHandler or other.

Added tag property to AbstractGoTween.cs. Then added removeTweenWithTag and tweensWithTag methods to Go.cs in order to allow the manipulation of currently active tweens via the tag property.

### CODE REVIEW

**Comment by zapdot** [comment]
Thanks for the PR. I'll check this sometime this weekend. :)

**Comment by rygo6** [comment]
If desired I will create a new example scene to demonstrate why I made GoDataType.cs, I realize now it may not be terribly obvious. But basically it's for instances like this:

	public void TransitionToTime()
	{	
		Go.removeTweenWithTag( "AnimatorEvent" );
	
		AnimatorStateInfo currentState = animator.GetCurrentAnimatorStateInfo( 0 );
		AnimatorClipInfo[] animationClips = animator.GetCurrentAnimatorClipInfo( 0 );
		AnimationClip animationClip = animationClips[0].clip;
	
		GoDataType goType = new GoDataType( currentState.normalizedTime );
		GoTween goTween = Go.to( goType, tranitionTime, new GoTweenConfig()
		                 	.floatProp( "floatType", time / animationClip.length, false)
		                	.setEaseType( GoEaseType.SineOut ) );		
		
		goTween.setOnUpdateHandler(
			c =>
			{
				animator.Play( stateName, 0, goType.floatType );	
			}        
		);
		
		goTween.setOnCompleteHandler( 
		   	c => 
		   	{ 
				animator.Play( stateName, 0, time / animationClip.length );	
			} 
		);   
		
		goTween.tag = "AnimatorEvent";		
	}

Where you are trying to tween something and the only way to interact with said thing is to pass a data type into its method. I could not conceive of any other way to do this with GoKit. But if there is, and GoDataType.cs is a bad idea, feel free to reject. But I would like to know the better alternative to accomplish this.

I was thinking an update following this would be to not rely on .floatProp with "floatType" as a parameter. But rather have it's own decorator method for each data type so you could just go .floatDataType( time, false).

**Comment by stevewoolcock** [comment]
Nice idea, I have done similar things in the past. I would consider calling it GoPropProxy, or GoProxyProp, or something along those lines. I feel that would make its purpose more obvious?

**Comment by zapdot** [comment]
Finally had some time to sit down and think about this. Couple knee jerk reactions:

* I like the idea, and I don't think we have any other magical way of handling this currently.
* I'm not thrilled with the name or the slew of properties in a class that you typically would probably use one field. 

What if we used generics? https://gist.github.com/zapdot/10bd29184a2ce765fe0f

**Comment by rygo6** [comment]
Closing in order to change code to the aforementioned GoProxyProp.

**Pull request closed without merging**
